name: keep_service_alive
on:
    schedule:
        - cron: '*/14 * * * *'

jobs:
    check_status:
        runs-on: ubuntu-latest
        steps:
            - name: 'Check status'
              run: curl https://foss-geo-api.onrender.com/api/status
